name: semantic-release using pnpm
description: GitHub Action for semantic-release using pnpm
author: cherryblossom000
branding:
  icon: 'package'
  color: gray-dark
inputs:
  branch:
    description: >-
      The branch on which releases should happen. It will override the branch attribute in your configuration file.
      If the attribute is not configured on both sides, the default is master.
    required: false
  semantic_version:
    description: The version range for semantic-release.
    required: false
    default: '17'
  extra_plugins:
    description: >-
      Extra plugins that are not included in the semantic-release defaults, separated by new lines. You can also specify
      the version range.
    required: false
  dry_run:
    description:
      Whether to run semantic release in `dry-run` mode. It will override the `dryRun` attribute in your configuration file.
    required: false
outputs:
  new_release_published:
    description: Whether a new release was published (`true` or `false`).
  new_release_version:
    description: Version of the new release.
  new_release_major_version:
    description: Major version of the new release.
  new_release_minor_version:
    description: Minor version of the new release.
  new_release_patch_version:
    description: Patch version of the new release.
runs:
  using: node12
  main: dist/index.js
