name: Build
on: [pull_request, push]
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Install
        run: npm i -g pnpm && pnpm i

      - name: Build
        run: pnpm run build

      - name: Upload build output
        uses: actions/upload-artifact@v1
        # if: github.ref == 'refs/heads/master'
        with:
          name: dist
          path: dist
  release:
    name: release
    needs: build
    # if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Download build output
        uses: actions/download-artifact@v1
        with:
          name: dist

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Install
        run: npm i -g pnpm && pnpm i -P

      - name: Semantic Release
        uses: ./
        with:
          branch: master
          extra_plugins: |
            @semantic-release/git
            @semantic-release/changelog
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}
